### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by ikkentim** [SampSharp/docs#25]
Linux installation notes

**Comment by ikkentim** [comment]
Unofficial core clr runtime: https://deploy.timpotze.nl/packages/dotnet20180628.zip

**Comment by ghost** [comment]
Problem: `No usable version of the libssl was found`
Solution: `sudo apt-get install libssl1.0.0:i386`

**Comment by MichaelBelgium** [comment]
Problem: `FailFast: Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.`
Solution: install the 32-bit version of libicu (for debian: `libicu-dev:i386`)

**Comment by ikkentim** [comment]
I've added a page for this: https://sampsharp.net/common-problems-on-linux
And I've added a link to the runtime in the running in production guide https://sampsharp.net/running-in-production
