### ISSUE TITLE
Player streaming don't work when player changed virtual world

### ISSUE THREAD

**Issue by sklawik** [SampSharp/docs#31]
Those 2 screenshots explain everything:
Player 1:
![2019 11 11-21 46](https://user-images.githubusercontent.com/56268694/68621345-d0708d80-04cf-11ea-8f2e-23cbb6944490.png)
Player 2:
![2019 11 11-21 46_01](https://user-images.githubusercontent.com/56268694/68621359-d6666e80-04cf-11ea-98a6-553b11d1a352.png)

In words:
We have 2 players, player 1 and player 2.
Player 1 and Player two, both are on VW 1.
Now player 1 changed his VW to VW 2.
He changes VW once again to go back toVW 1.
Now player 1 doesn't stream any players from VW 1.
And player 2 sees player 1. (both now are on VW 1).

**Comment by ikkentim** [comment]
This is not a sampsharp bug but a samp037dl bug. Also please report issues with sampsharp to https://github.com/ikkentim/sampsharp .
